name: cis680
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - astroid=2.4.2
  - async_generator=1.10
  - attrs=20.2.0
  - autopep8=1.5.4
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - bzip2=1.0.8
  - ca-certificates=2020.7.22
  - cairo=1.16.0
  - certifi=2020.6.20
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - dbus=1.13.16
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - ffmpeg=4.3.1
  - fontconfig=2.13.1
  - freetype=2.10.2
  - gettext=0.19.8.1
  - glib=2.66.0
  - gmp=6.2.0
  - gnutls=3.6.13
  - graphite2=1.3.13
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - h5py=2.10.0
  - harfbuzz=2.7.2
  - hdf5=1.10.6
  - icu=67.1
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=5.4.2
  - jasper=1.900.1
  - jedi=0.17.2
  - jinja2=2.11.2
  - joblib=0.16.0
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.6
  - jupyter_console=6.2.0
  - jupyter_core=4.6.3
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.2.0
  - krb5=1.17.1
  - lame=3.100
  - lazy-object-proxy=1.4.3
  - lcms2=2.11
  - ld_impl_linux-64=2.35
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=10.0.1
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.16
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libllvm10=10.0.1
  - libopencv=4.4.0
  - libpng=1.6.37
  - libpq=12.3
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.14
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - matplotlib=3.3.1
  - matplotlib-base=3.3.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - mysql-common=8.0.21
  - mysql-libs=8.0.21
  - nbclient=0.5.0
  - nbconvert=6.0.6
  - nbformat=5.0.7
  - ncurses=6.2
  - nest-asyncio=1.4.1
  - nettle=3.4.1
  - ninja=1.10.1
  - notebook=6.0.3
  - nspr=4.29
  - nss=3.57
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - opencv=4.4.0
  - openh264=2.1.1
  - openssl=1.1.1h
  - packaging=20.4
  - pandas=1.1.1
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.2.2
  - pixman=0.38.0
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.7
  - prompt_toolkit=3.0.7
  - py-opencv=4.4.0
  - pycodestyle=2.6.0
  - pygments=2.6.1
  - pylint=2.6.0
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyrsistent=0.17.3
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytorch=1.6.0
  - pytz=2020.1
  - pyzmq=19.0.1
  - qt=5.12.9
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - readline=8.0
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - send2trash=1.5.0
  - setuptools=49.6.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.33.0
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.1
  - torchvision=0.7.0
  - tornado=6.0.4
  - tqdm=4.49.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.35.1
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - x264=1!152.20180806
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
      - ipdb==0.13.3
      - ipython-genutils==0.2.0
      - parso==0.7.1
      - ptyprocess==0.6.0
      - pyqt5-sip==4.19.18
      - pyqtchart==5.12
      - pyqtwebengine==5.12.1
      - traitlets==5.0.3
